apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- gw-external.yaml
- gw-internal.yaml
- httproute-argocd.yaml
- httproute-longhorn.yaml
- httproute-redirect.yaml

generatorOptions:
  disableNameSuffixHash: true
