apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: libreddit-secrets
  namespace: libreddit
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: libreddit-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTHOG_API_KEY
    remoteRef:
      key: posthog-k8s
      property: libreddit_posthog_api_key
