apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vertical-pod-autoscaler

resources:
  - namespace.yaml
  - crds/vpa-v1-crd-gen.yaml

helmCharts:
  - name: vertical-pod-autoscaler
    repo: https://kubernetes.github.io/autoscaler
    version: 0.8.1
    releaseName: vpa
    namespace: vertical-pod-autoscaler
    valuesFile: values.yaml
    includeCRDs: true
