cluster_name: sweden
control_plane_endpoint: 192.168.1.116
worker:
  settings:
    machine:
      install:
        extraKernelArgs:
          - ipv6.disable=1
          - talos.dashboard.disabled=0
  nodes:
    - name: bee
      internal_ip: 192.168.1.118
      image_build:
        version: 1.11.2
        arch: amd64
        extensions:
          - siderolabs/amdgpu
          - siderolabs/amd-ucode
      settings:
        machine:
          install:
            disk: /dev/nvme0n1
    - name: intelnuc
      internal_ip: 192.168.1.117
      image_build:
        version: 1.11.2
        arch: amd64
        extensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
      settings:
        machine:
          install:
            disk: /dev/nvme0n1
    - name: think_c
      internal_ip: 192.168.1.223
      image_build:
        version: 1.11.2
        arch: amd64
        extensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
      settings:
        machine:
          install:
            disk: /dev/sda
        
controller:
  settings:
    machine:
      install:
        extraKernelArgs:
          - ipv6.disable=1
  nodes:
    - name: rpi_controller
      internal_ip: 192.168.1.116
      image_build:
        version: 1.11.2
        arch: siderolabs/sbc-raspberrypi
        extensions:
          - siderolabs/vc4
        options:
          configTxt: |-
            gpu_mem=128
            kernel=u-boot.bin
            arm_64bit=1
            arm_boost=1
            enable_uart=1
            dtoverlay=disable-bt
            dtoverlay=disable-wifi
            avoid_warnings=2
            dtoverlay=vc4-kms-v3d,noaudio
      settings:
        machine:
          certSANs:
            - 192.168.1.116
          install:
            disk: /dev/mmcblk0         
        
        