import yaml
import argparse
import os
import sys
import requests
import json
import collections.abc

DEFAULT_TALOS_CONFIGURATION_NAMES = {
    "worker": "worker.yaml",
    "controller": "controlplane.yaml"
}

TALOS_FACTORY_URL = "factory.talos.dev"

class IndentedDumper(yaml.Dumper):
    def increase_indent(self, flow=False, indentless=False):
        return super(IndentedDumper, self).increase_indent(flow, False)

# checks if machine configs were generated by talosctl 
# and creates a dictionary of file paths if they exist
# otherwise, sys.exit(1)

def create_configurations(node_file_dictionary, folder_path):
    if not os.path.isdir(folder_path):
        os.mkdir(folder_path)
    
    for node in node_file_dictionary:
        for file_name, file_value in node.items():
            with open(f"{folder_path}/{file_name}.yaml", 'w') as outfile:
                yaml.dump(file_value, outfile, default_flow_style=False, sort_keys=False, Dumper=IndentedDumper)

def update_nested_dictionary_key(current_dictionary, update_dictionary):
    for key, value in update_dictionary.items():
        if isinstance(value, collections.abc.Mapping):
            current_dictionary[key] = update_nested_dictionary_key(current_dictionary.get(key, {}), value)
        else:
            current_dictionary[key] = value
    return current_dictionary

def generate_talos_image_id(image_build):
    request_body = dict({
        "customization": {
            "systemExtensions": {
                "officialExtensions": image_build.get("extensions", [])
            }
        }
    })
    # TODO - add "options" to request body.
    response = requests.post(f"https://{TALOS_FACTORY_URL}/schematics", json=request_body)
    if response.status_code >= 200 and response.status_code <= 300:
        json_response = json.loads(response.content)
        image_id = json_response["id"]
        print(image_id)
        print(f"{response} is here")
    else:
        raise Exception(f"unable to generate image id due to {response.reason}")
    return image_id

def create_node_configurations(default_mapping, global_settings, defined_configurations):
    configured_nodes = []
    for node in defined_configurations:
        node_configuration = default_mapping.copy()
        node_image_id = generate_talos_image_id(node["image_build"])
        node["settings"]["machine"]["install"]["image"] = f"{TALOS_FACTORY_URL}/metal-installer/{node_image_id}:{node['image_build']['version']}"
        update_nested_dictionary_key(node_configuration, global_settings)
        update_nested_dictionary_key(node_configuration, node["settings"])
        configured_nodes.append({node["name"]: node_configuration})
        
    return configured_nodes

def get_file_path_mappings(user_defined_configuration_path, talos_configuration_path=None):
    mappings = {}
    if talos_configuration_path:
        path_prefix = talos_configuration_path
    else:
        path_prefix = ""

    if os.path.isfile(f"{path_prefix}{user_defined_configuration_path}"):
        with open(f"{path_prefix}{user_defined_configuration_path}", encoding="utf-8") as file_stream:
                mappings["user_configuration_file"] = yaml.safe_load(file_stream)
    else:
        print(f"file path for user configuration is invalid at {user_defined_configuration_path}")
        
    for node_type, talos_configuration_file_name in DEFAULT_TALOS_CONFIGURATION_NAMES.items():
        file_path = f"{path_prefix}{talos_configuration_file_name}"
        if os.path.isfile(file_path):
            with open(file_path, encoding="utf-8") as file_stream:
                mappings[node_type] = yaml.safe_load(file_stream)
        else:
            print(f"file path for {node_type} does not exist at {file_path}")
            sys.exit(1)

    return mappings

def create_talos_configuration_files(talos_configuration_file_mappings, worker_path, controller_path):

    # create control plane files
    controller_nodes = create_node_configurations(
        talos_configuration_file_mappings["controller"], 
        talos_configuration_file_mappings["user_configuration_file"]["controller"].get("settings", {}), 
        talos_configuration_file_mappings["user_configuration_file"]["controller"]["nodes"]
    )
    
    worker_nodes = create_node_configurations(
        talos_configuration_file_mappings["worker"], 
        talos_configuration_file_mappings["user_configuration_file"]["worker"].get("settings", {}), 
        talos_configuration_file_mappings["user_configuration_file"]["worker"]["nodes"]
    )
    
    create_configurations(controller_nodes, controller_path)
    create_configurations(worker_nodes, worker_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--config-path")
    parser.add_argument("--talos-defaults-path", default=None, required=False)
    parser.add_argument("--worker-path", default="workers", required=False)
    parser.add_argument("--controller-path", default="controllers", required=False)

    args = parser.parse_args()

    talos_configuration_file_mappings = get_file_path_mappings(args.config_path, args.talos_defaults_path)
    print("Generating talos configuration files form config.yaml")
    create_talos_configuration_files(talos_configuration_file_mappings, args.worker_path, args.controller_path)
