apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: honeycomb-api-key
  namespace: opentelemetry
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: honeycomb-api-key
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: honeycomb
      property: api-key
