manager:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  serviceMonitor:
    enabled: false
    additionalLabels:
      release: kube-prometheus-stack

admissionWebhooks:
  certManager:
    enabled: true
