---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  bgpInstances:
    - name: "opnsense"
      localASN: 64514
      peers:
        - name: "opnsense-router"
          peerAddress: "192.168.1.1"
          peerASN: 64514
          peerConfigRef:
            name: "lb-advertisement"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: lb-advertisement
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  ebgpMultihop: 1
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "true"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lb-adv
  labels:
    advertise: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ClusterIP
          - LoadBalancerIP
      selector:
        matchLabels: {}
