apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - nolock
    - tcp
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nconnect=16
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-media
    volumeAttributes:
      server: "192.168.1.59"
      share: "/mnt/user/k8s/jellyfin-media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: jellyfin-media
  storageClassName: ""