apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-auth-es
  namespace: jellyfin
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: jellyfin-auth
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: jellyfin
        property: apiKey
