#!/usr/bin/env bash
# validate-argocd-apps.sh — Catches duplicate Application names,
# sync wave gaps, and AppSet/standalone path overlaps.
#
# Run from repo root: ./scripts/validate-argocd-apps.sh

set -euo pipefail

APPS_DIR="infrastructure/controllers/argocd/apps"
ERRORS=0

echo "=== ArgoCD Application Validation ==="
echo ""

# ─────────────────────────────────────────────
# 1. Check for duplicate Application names
#    (standalone apps vs AppSet-generated apps)
# ─────────────────────────────────────────────
echo "--- Check 1: Duplicate Application Names ---"

# Extract standalone Application names
standalone_names=()
standalone_paths=()
for f in "$APPS_DIR"/*-app.yaml "$APPS_DIR"/*connect.yaml "$APPS_DIR"/external-secrets.yaml "$APPS_DIR"/kyverno-app.yaml; do
  [ -f "$f" ] || continue
  name=$(grep -A1 "^  name:" "$f" 2>/dev/null | head -1 | sed 's/.*name: //' | tr -d "'\"" | xargs || true)
  path=$(grep "path:" "$f" 2>/dev/null | grep -v "repoURL\|targetRevision\|manifest" | head -1 | sed 's/.*path: //' | tr -d "'\"" | xargs || true)
  if [ -n "$name" ] && [ -n "$path" ]; then
    standalone_names+=("$name")
    standalone_paths+=("$path")
  fi
done

# Extract AppSet generator paths and their template name patterns
for appset in "$APPS_DIR"/*-appset.yaml; do
  [ -f "$appset" ] || continue
  appset_name=$(basename "$appset")

  # Extract paths from git directory generators
  while IFS= read -r appset_path; do
    appset_path=$(echo "$appset_path" | sed 's/.*path: //' | tr -d "'\"" | xargs)
    [ -z "$appset_path" ] && continue

    # The generated Application name is {{path.basename}}
    generated_name=$(basename "$appset_path")

    # Check if this name conflicts with a standalone Application
    for i in "${!standalone_names[@]}"; do
      if [ "${standalone_names[$i]}" = "$generated_name" ]; then
        echo "  ERROR: '$generated_name' is defined as both:"
        echo "         - Standalone Application (in apps/ directory)"
        echo "         - Generated by $appset_name (path: $appset_path)"
        echo "         The AppSet will overwrite the standalone app's sync wave!"
        echo ""
        ERRORS=$((ERRORS + 1))
      fi
    done
  done < <(grep "path:" "$appset" | grep -v "repoURL\|targetRevision\|manifest\|exclude\|template" | grep "infrastructure/\|monitoring/\|my-apps/" || true)
done

[ $ERRORS -eq 0 ] && echo "  OK: No duplicate Application names found"
echo ""

# ─────────────────────────────────────────────
# 2. Check sync wave continuity
#    (no unexpected gaps in the wave sequence)
# ─────────────────────────────────────────────
echo "--- Check 2: Sync Wave Continuity ---"

waves=()
for f in "$APPS_DIR"/*.yaml; do
  [ -f "$f" ] || continue
  wave=$(grep "sync-wave:" "$f" 2>/dev/null | head -1 | sed 's/.*sync-wave: *//' | tr -d '"' | xargs || true)
  if [ -n "$wave" ]; then
    waves+=("$wave")
  fi
done

# Sort and deduplicate
mapfile -t sorted_waves < <(printf '%s\n' "${waves[@]}" | sort -n | uniq)
echo "  Waves found: ${sorted_waves[*]}"

# Check for gaps > 1 between consecutive waves
prev=""
for w in "${sorted_waves[@]}"; do
  if [ -n "$prev" ]; then
    gap=$((w - prev))
    if [ $gap -gt 1 ]; then
      echo "  WARNING: Gap between wave $prev and $w (missing wave(s): $(seq $((prev + 1)) $((w - 1)) | tr '\n' ',' | sed 's/,$//'))"
    fi
  fi
  prev=$w
done
echo ""

# ─────────────────────────────────────────────
# 3. Check kustomization.yaml lists all files
# ─────────────────────────────────────────────
echo "--- Check 3: All YAML files listed in kustomization.yaml ---"

kustomization="$APPS_DIR/kustomization.yaml"
if [ -f "$kustomization" ]; then
  for f in "$APPS_DIR"/*.yaml; do
    [ -f "$f" ] || continue
    fname=$(basename "$f")
    [ "$fname" = "kustomization.yaml" ] && continue
    # Skip non-Application files (Helm values, etc.)
    grep -q "kind: Application\|kind: ApplicationSet\|kind: AppProject" "$f" 2>/dev/null || continue
    # argocd.yaml is intentionally excluded (circular dependency with root.yaml)
    [ "$fname" = "argocd.yaml" ] && continue
    if ! grep -q "$fname" "$kustomization" 2>/dev/null; then
      echo "  ERROR: $fname exists but is NOT listed in kustomization.yaml"
      echo "         This file will NEVER be deployed by ArgoCD!"
      ERRORS=$((ERRORS + 1))
    fi
  done
  echo "  OK: All YAML files are listed in kustomization.yaml"
fi
echo ""

# ─────────────────────────────────────────────
# 4. Check internal resource waves don't
#    contradict their Application wave
# ─────────────────────────────────────────────
echo "--- Check 4: Internal sync-wave consistency ---"

for f in "$APPS_DIR"/*-app.yaml "$APPS_DIR"/pvc-plumber-app.yaml; do
  [ -f "$f" ] || continue
  app_name=$(grep "name:" "$f" | head -1 | sed 's/.*name: //' | tr -d "'\"" | xargs)
  app_wave=$(grep "sync-wave:" "$f" 2>/dev/null | head -1 | sed 's/.*sync-wave: *//' | tr -d '"' | xargs || true)
  app_path=$(grep "path:" "$f" 2>/dev/null | grep -v "repoURL\|targetRevision" | head -1 | sed 's/.*path: //' | tr -d "'\"" | xargs || true)

  [ -z "$app_path" ] && continue
  [ ! -d "$app_path" ] && continue

  # Check namespace.yaml for mismatched wave
  ns_file="$app_path/namespace.yaml"
  if [ -f "$ns_file" ]; then
    ns_wave=$(grep "sync-wave:" "$ns_file" 2>/dev/null | head -1 | sed 's/.*sync-wave: *//' | tr -d '"' | xargs || true)
    if [ -n "$ns_wave" ] && [ "$ns_wave" != "$app_wave" ]; then
      echo "  WARNING: $app_name Application is wave $app_wave, but $ns_file has sync-wave: $ns_wave"
      echo "           The Application wave controls deployment order. Namespace annotation is misleading."
    fi
  fi
done
echo ""

# ─────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────
echo "=== Summary ==="
if [ $ERRORS -gt 0 ]; then
  echo "  FAILED: $ERRORS error(s) found"
  exit 1
else
  echo "  PASSED: All checks passed"
  exit 0
fi
