apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt
  namespace: k8sgpt
spec:
  ai:
    enabled: true
    model: "nothink - qwen3.5"
    backend: localai
    baseUrl: http://llama-cpp-service.llama-cpp.svc.cluster.local:8080/v1
    anonymized: false
    language: english
    maxTokens: "16384"
  filters:
    - Pod
    - Service
    - Deployment
    - StatefulSet
    - ReplicaSet
    - Job
    - PersistentVolumeClaim
    - Node
    - CronJob
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: "202602281832@sha256:c9aa60521c0389c94d27019bd9dde5fd2e96eb5e2a31d36eee398ce8e424c084"
